### ISSUE TITLE
Implementing Sieve of Eratosthenes (C/C++/Java/Python)

### ISSUE THREAD

**Issue by GnikDroy** [Asiatik/codezilla#115]

**Comment by GnikDroy** [comment]
I will be doing this

**Comment by GnikDroy** [comment]
Forgot to mention I will be doing this for C/c++/java and python

**Comment by thakurdivyanshu** [comment]
can i work on it

**Comment by GnikDroy** [comment]
@thakurdivyanshu I am working on this for c/c++/java and python. You can use another language or make a different algorithm
