### ISSUE TITLE
Add readme for java builder pattern

### ISSUE THREAD

**Issue by tstreamDOTh** [Asiatik/codezilla#128]

**Comment by DanielTamkin** [comment]
Can you elaborate on this issue? Would love to help out.

**Comment by tstreamDOTh** [comment]
@DanielTamkin Thanks for showing interest I think this has already been assigned. You can pick up any other issue or feel free to create one yourself wherever you feel you can contribute

**Comment by tstreamDOTh** [comment]
@DanielTamkin Thanks for showing interest I think this has already been assigned. You can pick up any other issue or feel free to create one yourself wherever you feel you can contribute

**Comment by tstreamDOTh** [comment]
@DanielTamkin You can use https://orgmanager.miguelpiedrafita.com/join/36604391 to join Asiatik
