### ISSUE TITLE
DP Ways to decode CPP

### ISSUE THREAD

**Issue by find3rskeeper** [Asiatik/codezilla#147]
## Title: 
Ways to decode an integer string into a character string
https://www.interviewbit.com/problems/ways-to-decode/

## Body:
**Problem Statement**
Ways to Decode

A message containing letters from A-Z is being encoded to numbers using the following mapping:

'A' -> 1
'B' -> 2
...
'Z' -> 26

Given an encoded message containing digits, determine the total number of ways to decode it.

Example :

Given encoded message "12", it could be decoded as "AB" (1 2) or "L" (12).

The number of ways decoding "12" is 2.

I am working on this problem

**Comment by find3rskeeper** [comment]
I am working on this issue

**Comment by GnikDroy** [comment]
@find3rskeeper Thanks for contributing. You should have opened a documentation issue though. Keep that in mind next time. Could you edit the issue to let us know what exactly you are working on? It will be hard to keep track of once we have many issues.

**Comment by find3rskeeper** [comment]
Hey Thanks for the reply. I saw an issue on a coding website and wanted to contribute with the solution. It's  the solution for the problem mentioned in the file that I commited. Should I describe the question in this issue. Also would this be a documentation issue?

**Comment by GnikDroy** [comment]
@find3rskeeper Sorry this was not a documentation issue. My bad. But you need to describe the problem you are solving. A solution without a question is not useful. Please add the question along as well and put it up. Thank you for contributing.

**Comment by find3rskeeper** [comment]
@GnikDroy I have edited the description. Is there any other requirement.  Thanks

**Comment by GnikDroy** [comment]
@find3rskeeper This is okay.
