### ISSUE TITLE
Implement Heap Sort (Python)

### ISSUE THREAD

**Issue by GnikDroy** [Asiatik/codezilla#202]
## Implement Heap Sort in Python

We need a simple heap sort algorithm written in Python for our repository.

This issue is great for beginners looking to contribute in open source. If you wish to fix this issue please comment that you are working on it. Please read the readme.md and contributing.md files to learn how to contribute.

If you wish to contribute another algorithm or the same algorithm in a different language, please see if it hasn't been implemented and issue a new request if no issue has been made.

**If you are going to work on the issue yourself, make sure you comment on the issue to let others know.**

**Comment by punkyoon** [comment]
I would like to work on this!...

**Comment by GnikDroy** [comment]
@punkyoon I will leave it to you then. Thank you
