### ISSUE TITLE
Implement Merge Sort (Python)

### ISSUE THREAD

**Issue by GnikDroy** [Asiatik/codezilla#204]
## Implement Merge Sort in Python

We need a simple merge sort algorithm written in Python for our repository.

This issue is great for beginners looking to contribute in open source. If you wish to fix this issue please comment that you are working on it. Please read the readme.md and contributing.md files to learn how to contribute.

If you wish to contribute another algorithm or the same algorithm in a different language, please see if it hasn't been implemented and issue a new request if no issue has been made.

**If you are going to work on the issue yourself, make sure you comment on the issue to let others know.**

**Comment by aayushsinha44** [comment]
I would like solve this and want this task to be assigned to me.

**Comment by GnikDroy** [comment]
@aayushsinha44 All right. I will leave it to you.

**Comment by GnikDroy** [comment]
@prkhrv No problem man. Happens to the best of us. You are a first-time contributor so no problem.

**Comment by vivekptnk** [comment]
Can I work on this?
