### ISSUE TITLE
Implement Stack (Python)

### ISSUE THREAD

**Issue by GnikDroy** [Asiatik/codezilla#205]
## Implement Stack in Python

We need a simple stack implementation written in Python for our repository.

This issue is great for beginners looking to contribute in open source. If you wish to fix this issue please comment that you are working on it. Please read the readme.md and contributing.md files to learn how to contribute.

If you wish to contribute another algorithm/data structure or the same algorithm in a different language, please see if it hasn't been implemented and issue a new request if no issue has been made.

**If you are going to work on the issue yourself, make sure you comment on the issue to let others know.**

**Comment by asterisk30** [comment]
i would like to work on this. please assign this this task to me.

**Comment by aayushsinha44** [comment]
i have solved the problem and pushed it with branch "stack-python".

**Comment by GnikDroy** [comment]
@aayushsinha44 Please tell everyone that you are working on it before putting up a pull request. This is your first time, so you are excused. Please take that into consideration from next time

**Comment by GnikDroy** [comment]
@asterisk30 So sorry but someone seems to have already solved the issue. Can you please take something else?
