### ISSUE TITLE
Implement Heap (Python)

### ISSUE THREAD

**Issue by GnikDroy** [Asiatik/codezilla#206]
## Implement Heap in Python

We need a simple heap implementation written in Python for our repository.

This issue is great for beginners looking to contribute in open source. If you wish to fix this issue please comment that you are working on it. Please read the readme.md and contributing.md files to learn how to contribute.

If you wish to contribute another algorithm/data structure or the same algorithm in a different language, please see if it hasn't been implemented and issue a new request if no issue has been made.

**If you are going to work on the issue yourself, make sure you comment on the issue to let others know.**

**Comment by prkhrv** [comment]
@GnikDroy  I would like to Contribute on this.

**Comment by GnikDroy** [comment]
@prkhrv All right. I will leave it to you then
