### ISSUE TITLE
Implementing MergeSort Algorithm in C++

### ISSUE THREAD

**Issue by MounikaPonugoti** [Asiatik/codezilla#31]

**Comment by sarkararpan710** [comment]
Do you want this Algorithm to be implementable on arrays or linked lists?
A much better algorithm to implement arrays is Quick Sort and for linked lists it is Merge Sort.

**Comment by MounikaPonugoti** [comment]
I thought that all the sorting (at least basic) algorithms  are going to be implemented in the future. So, to cope with existing implantation, I planned to do with arrays. I can also do with linked lists. Which one should I do? arrays or linked lists or both?

**Comment by abhinav-adtechs** [comment]
Hey, 
Thanks for being interesting in contributing to codezilla! 

Go for both of them, it'll be great!

**Comment by MounikaPonugoti** [comment]
Thank you for the opportunity to contribute.
Issue #31 is actually implementing merge sort with arrays and linked lists. I am almost ready with linked list version. However, issue #31 is closed. Should I open new one or just move on?
