### ISSUE TITLE
Trie Tree implementation in C

### ISSUE THREAD

**Issue by shubhamguptaji** [Asiatik/codezilla#333]
## Title: 
Trie Tree (C)

## Body:
 Trie Tree implementation in C

**Comment by jonumhills** [comment]
can u give a detail about the issue!!!

**Comment by shubhamguptaji** [comment]
add Trie tree data structure implementation in C language

**Comment by jonumhills** [comment]
i am on it

**Comment by shubhamguptaji** [comment]
good luck
