### ISSUE TITLE
Include README in each algorithm folder

### ISSUE THREAD

**Issue by GnikDroy** [Asiatik/codezilla#38]
Since this is a huge collection of algorithms, It would be better to include a README in each algorithm folder that includes how the algorithm works. We can also add the time/space complexity if possible and some basic usages of the code. This will prevent the code from becoming a huge mess and will auto document it as well.

**Comment by abhinav-adtechs** [comment]
I think code level documentation supports what you require. But this can be good for people who are just navigating on GitHub. 

Nevertheless, this is good enhancement. Feel free to raise a PR for the same.
