### ISSUE TITLE
Add algorithms for mathematical operations

### ISSUE THREAD

**Issue by GnikDroy** [Asiatik/codezilla#48]
As the title suggests, I propose to add a new folder named Mathematical_Algorithms(??). Is the '_' required? We should replace it with spaces instead. Also is appending Algorithms to the folder required? 
We could name it simply 'Math' for readability. It can hold algorithms for finding/verifying primes, gcd, totient functions, zeta functions, partitions, multiplying matrices, finding eigenvalues/eigenvectors etc.

**Comment by tstreamDOTh** [comment]
@GnikDroy Break this issue into multiple issues and raise PR for each algo/function
