### ISSUE TITLE
Request to start contributing 

### ISSUE THREAD

**Issue by Abhishekguragol** [Asiatik/codezilla#7]
I would like to contribute to the searching algorithms. Since this is my first time i wanted to pick something easy.

**Comment by tstreamDOTh** [comment]
@Abhishekguragol Welcome. Create an issue, fork the repo, commit and make a PR.

**Comment by mrkarna** [comment]
Hi,
I would like to write up codes under dynamic programming and graphs algorithms section. Will you please help as I am new to open source.
