### ISSUE TITLE
Add DAO pattern for Java

### ISSUE THREAD

**Issue by tstreamDOTh** [Asiatik/codezilla#77]

**Comment by mrFunkyWisdom** [comment]
@tstreamDOTh I will do this one :)

**Comment by tstreamDOTh** [comment]
@mrFunkyWisdom  @sladyn98  This is already assigned. Feel free to create an issue for some other pattern and work on it. Join Asiatik at https://orgmanager.miguelpiedrafita.com/join/36604391
